version: '3.7'

services:
    usedmarket-backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/usedMarket/src
        ports:
            - 4000:4000
        env_file:
            - ./.env

    usedmarket-database:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'usedMarket'
            MYSQL_ROOT_PASSWORD: 'tjddnjs'
        ports:
            - 3307:3306
